services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: campgrounds
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  scraper:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/campgrounds
    command: python scraper.py

volumes:
  pgdata:
